version: "3.7"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command:
      [
        "bash",
        "-c",
        'echo ''alias ll="ls -l"'' >> ~/.bashrc && pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload --workers 1',
      ]
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - 25432:5432
    volumes:
      - ./docker/postgres/init.d:/docker-entrypoint-initdb.d
      - ./docker/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: admin
      TZ: "Asia/Tokyo"
    hostname: postgres
    restart: always
    user: root

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    user: "$UID:$GID"
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
